# Generated by Django 5.0.7 on 2024-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='Buildings',
        ),
        migrations.AlterModelOptions(
            name='apartments',
            options={'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterModelOptions(
            name='apartmentsimages',
            options={'verbose_name': "Apartment's image", 'verbose_name_plural': "Apartment's images"},
        ),
        migrations.AlterModelOptions(
            name='buildings',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterField(
            model_name='apartments',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+'), ('Студия', 'Студия')], default='1', max_length=20, verbose_name='Rooms'),
        ),
    ]
